@startuml

class User {
    - name: String
}

class Customer {
    - contact: String
}

class Machine {}

class Administrator {}


class Order {
    - status: OrderStatus
    - creationDate: Date
}

class Product {
    - name: String
    - order: Order
    - state: ProductState
}

enum OrderStatus {
    CREATED
    PENDING
    IN_PROGRESS
    COMPLETED
}

enum ProductState {
    ORDERED
    READY
}

User <|-- Customer
User <|-- Machine
User <|--  Administrator

Customer "1" -- "*" Order : has orders
Order "1" -- "*" Product : contains products

@enduml