@startuml

entity User {
    + id: int [PK]
    --
    name: String
    contact: String
}


entity Customer {
    + id: int [PK]
    --
    name: String
    contact: String
    user_id: int [FK]
}

entity Order {
    + id: int [PK]
    --
    status: OrderStatus
    creationDate: Date
}

entity Product {
    + id: int [PK]
    --
    name: String
    state: ProductState
    order_id: int [FK]
}

enum OrderStatus {
    CREATED
    PENDING
    IN_PROGRESS
    COMPLETED
}

enum ProductState {
    ORDERED
    READY
}

User ||-|| Customer
Customer ||--o{ Order : "places"
Order ||--o{ Product : "contains"

@enduml