services:
  web:
    build: .
    ports:
      - 9001:9000
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - redis

volumes:
  redis_data:

networks:
  redis:
