@startuml

state Open
state Closed
state Locked


[*] --> Open: Insert


Open --> Closed : Close
Closed --> Open : Open
Closed --> Locked: Lock
Locked --> Closed: Unlock

Open --> [*] : Remove




@enduml