@startuml

[*] --> Off: Install

state Broken
state On
state Off


Off --> On: Switch on
On --> Off: Switch off
On --> Broken: Break
Broken --> [*]: Remove

Off --> [*] : Remove

@enduml
